/* V2 · 分析说明文档（脱敏，供「分析说明」按钮展示）
 * 挂 globalThis.JVHelpContent = { equiv: HTML字符串, corr: HTML字符串, markdownLinks:... }
 * 渲染端直接 innerHTML；内容为原理/示例/方法，示例数据与命名已脱敏（PVK-S1 等为假样品名）。
 * i18n：中文全文在 equivHelp/corrHelp；英文版 equivHelp_en（全文级）/ corrHelp_en（精炼英译，覆盖全部章节，细节少于中文版）——渲染端 lang==='en' 取 _en 缺失时回退中文（equiv_ui.js openHelp）。
 */
(function (global) {
  'use strict';

  var equivHelp = [
    '<div class="h-warn">⚠ <b>读数前必读：</b>本页所有 n/J₀ 均为<b>表观值</b>（亮态对数线性法提取，受迟滞、Rs、离子迁移影响），正反扫迟滞差显著时诊断卡会出现 ⚠ 警示。n/J₀ 只用于<b>同批同扫描条件的相对比较</b>，请勿当作本征参数直接引用；Suns-Voc 是分析复合相关理想因子行为的重要参照方法之一，可显著降低 Rs 对结果的干扰，但在钙钛矿中仍可能受离子-电子耦合与界面状态影响，宜与暗态 JV、阻抗谱或稳态/漂移扩散分析交叉验证。诊断卡出现 ⚠ 迟滞警示属预期，不代表器件不合格。</div>',
    '<h3>关于「表观参数与迟滞诊断（工程筛选）」</h3>',
    '<p>光伏电池（钙钛矿等）的 JV 曲线，常用「单二极管等效电路」来描述——用一组参数把一条曲线压缩成几个有物理含义的数字，从而回答：<b>这台器件、这个条件的效率损失到底出在哪一环？</b></p>',
    '<p><b>定位</b>：本页是<b>工程筛选与异常定位</b>工具，用于同批器件的相对比较与排查方向提示，<b>不是</b>本征参数提取手段——亮态、有限扫描速率下得到的表观指标（见注意事项）不能直接当作器件本征特性引用。</p>',
    '<div class="h-eq">J = J<sub>L</sub> − J<sub>0</sub>[exp((V + J·R<sub>s</sub>)/a) − 1] − (V + J·R<sub>s</sub>)/R<sub>sh</sub>，　a = n·kT/q</div>',
    '<h3>四个关心的参数</h3>',
    '<table><tr><th>参数</th><th>物理含义</th><th>偏高的异常表现</th><th>对应排查方向</th></tr>',
    '<tr><td><b>Rs</b> 串联电阻</td><td>体/接触/电极的串联阻抗，越大越限流</td><td>FF 与 Voc 双降</td><td>正面电极、传输层接触、银栅</td></tr>',
    '<tr><td><b>Rsh</b> 并联电阻</td><td>漏电通路，越小短路越严重</td><td>针孔/漏电，Jsc 与 FF 受损</td><td>界面钝化、退火、膜厚均匀性</td></tr>',
    '<tr><td><b>n</b> 理想因子</td><td>表观理想因子（亮态、有限扫描速率，受迟滞/离子过程影响）</td><td>Voc 损耗</td><td>界面/体缺陷复合</td></tr>',
    '<tr><td><b>J₀</b> 饱和电流密度</td><td>表观 J₀（外推型，由拟合直线截距外推到 V=0 得到；绝对阈值 1e-5 mA/cm² 为经验阈值/未标定，优先使用相对 Base 的 Δlog₁₀J₀ 或批内分位数比较）</td><td>Voc 偏低</td><td>钝化层质量、能级对齐</td></tr></table>',
    '<h3>计算方法</h3>',
    '<p><b>Rs / Rsh</b>：直接用仪器原始数据给出的 Rs/Rsh 列；已按器件面积换算面积归一化口径（Ω·cm²，= 仪器值 × 面积），供跨批次与绝对阈值参考（当前批面积 0.0625 cm²）。仪器值目前与「绝对 Ω」口径自洽（详见「Rs 修正」章节的单位说明），字段定义待仪器手册确认。</p>',
    '<p><b>n / J₀</b>：用「亮态对数线性法」：在曲线 J &lt; 0 的上拐区，暗电流 J<sub>d</sub> ≈ J<sub>sc</sub>−J ≈ J₀·exp(V/(n·kT/q))，对 <code>ln(J<sub>sc</sub>−J) ~ V</code> 做线性回归——斜率得出 n，截距得出 J₀。这个办法稳定、可解释，适用于<b>同一批器件的相对工程比较</b>；提取的是<b>表观参数</b>（详见注意事项）。</p>',
    '<h3>双方向拟合（正扫 / 反扫 / 汇总）</h3>',
    '<p><b>正扫与反扫分别拟合</b>：同一条器件同时给出反扫 n<sub>rev</sub>/J₀,rev 与正扫 n<sub>fwd</sub>/J₀,fwd。</p>',
    '<ul><li><b>汇总口径</b>：同时有正反扫的器件，n 取两方向<b>算术平均</b>、J₀ 取两方向<b>几何平均</b>（log₁₀ 平均）作为该器件的 n/J₀——这是本页图表与诊断卡的默认口径；仅单方向扫描的器件，使用该方向的数据（诊断卡会注明方向）。正扫与反扫对应不同扫描历史下的器件状态，平均值是<b>统计汇总</b>，不代表某个单一物理状态。</li>',
    '<li><b>迟滞差</b>：正反扫数据均有效的器件给出 Δn = |n<sub>rev</sub>−n<sub>fwd</sub>| 与 Δlog₁₀J₀ = |log₁₀J₀,rev − log₁₀J₀,fwd|，条件级取中位数显示在诊断卡「双方向」行。</li>',
    '<li><b>方向性迟滞</b>：除绝对差 Δn/Δlog₁₀J₀ 外，同时给出有符号方向差 δn = n<sub>fwd</sub> − n<sub>rev</sub>、δlog₁₀J₀ = log₁₀J₀,fwd − log₁₀J₀,rev，并统计正扫更高的器件比例——用于区分「迟滞大但方向随机」与「整批系统性正扫偏高」，后者更值得工艺排查。</li>',
    '<li><b>拟合质量分级</b>：n/J₀ 结果按拟合质量分为 <b>A / B / C</b> 三级——<b>A 可信</b>（可参与条件统计）、<b>B 参考</b>、<b>C 仅趋势</b>（灰显）；判定依据为有效点数 N、电压跨度 ΔV、置信区间宽度与窗口稳定性，阈值为例示值、需按仪器标定。诊断卡「拟合覆盖」行显示成功拟合数/总数与 A/B/C 占比。</li>',
    '<li><b>阈值与警示</b>：Δn 与 Δlog₁₀J₀ 尺度不同，已拆为两个阈值：<b>Δn 阈值</b>（默认 <b>0.5</b>，触发主警报）与 <b>Δlog₁₀J₀ 阈值</b>（默认 <b>1.0</b> = 10 倍，仅作支持证据/辅助提示，不单独触发主警报），均可在「🎨 格式 → 诊断阈值」调整 → 诊断卡出现 <b>⚠ 迟滞警示</b>，提示 n/J₀ 为表观值、偏高可能含迟滞/测量假象。阈值越大误报越少但可能漏报，越小越敏感但易误报——它只影响「谨慎解读」提示，<b>不判器件不合格</b>。</li>',
    '<li><b>重要</b>：迟滞显著依赖<b>扫描速率、扫描范围、预偏压/预处理与方向顺序</b>，且随扫描速率可能呈<b>非单调变化</b>（过慢接近准稳态、过快离子来不及响应，中间时间尺度可能最显著）；因此跨测试协议的 Δn 与 Δlog₁₀J₀ 不可直接比较，同批同扫描条件比较才成立。</li></ul>',
    '<h3>Rs 修正（可选）</h3>',
    '<p>串联电阻 Rs 使结电压偏离外施电压：<b>V<sub>int</sub> = V − J·R<sub>s</sub></b>（J&lt;0，故 V<sub>int</sub>&gt;V）；开启后按此修正电压轴重新拟合 n/J₀。</p>',
    '<p><b>位置与默认</b>：开关位于「🎨 格式 → 诊断阈值 → Rs 修正」，<b>默认关闭</b>。开启后，本页 4 张分布图与诊断卡<b>即时以修正口径重算</b>，图表标题会标注「Rs 修正」。</p>',
    '<p><b>适用建议</b>：本工具的拟合窗口（|J| 为 Jsc 的 10%~90%）已避开靠近 Jsc 的串联电阻干扰最强区段；对典型批次实测，当前单项 Rs 修正（即使按正确面积归一化口径）未改善拟合质量，保留默认关闭，以维持本方法作为经验型相对指标的稳定口径。仅当器件 Rs 较大、或拟合窗口被迫贴近 Jsc 的批次，可尝试开启，并以拟合线性（r²）与参数物理合理性复核。</p>',
    '<p><b>单位说明</b>：Rs 修正使用面积归一化值 Rs·A（Ω·cm²）。仪器 Rs 与「绝对 Ω」口径自洽（当前批面积 0.0625 cm²，Rs·A 中位约 2 Ω·cm²），字段定义仍待仪器手册/独立斜率复核；近 Jsc 局部斜率交叉验证结果：斜率 ≈ Rsh·A（1484 vs 1650 Ω·cm²），支持 Rsh 的绝对 Ω 口径。</p>',
    '<h3>示例</h3>',
    '<p>某批样品：<b>PVK-S1（对照）</b>与 <b>PVK-S2</b> 各 12 台，中位参数（n/J₀ 为双方向汇总口径）：</p>',
    '<table><tr><th>样品</th><th>Rsh (Ω)</th><th>Rs (Ω)</th><th>n 主值</th><th>正扫/反扫 n</th><th>Δn</th><th>J₀ (mA/cm²)</th><th>读数</th></tr>',
    '<tr><td>PVK-S1</td><td>≈22k</td><td>≈31</td><td>1.87</td><td>2.11 / 1.63</td><td>0.48</td><td>3e−9</td><td>Δn 接近阈值 0.5 → 带迟滞提示，健康</td></tr>',
    '<tr><td>PVK-S2</td><td>≈15k</td><td>≈33</td><td>2.14</td><td>2.4 / 1.9</td><td>0.5</td><td>2e−8</td><td>n/J₀ 偏高 → 建议查钝化/退火（受迟滞影响，谨慎）</td></tr></table>',
    '<p>结论方向：PVK-S2 的差异不在接触（Rs 相近）、也不在漏电（Rsh 尚可），而在<b>复合变强（n、J₀ 升高）</b>——直接指向钝化/界面处理，而不是改吸收层；但两组 Δn 都接近阈值，表观 n 含迟滞成分，最终结论需结合同条件正反扫曲线与 Suns-Voc 复核。</p>',
    '<h3>使用方法</h3>',
    '<ul><li>点工具栏「⚡ 等效电路分析」打开；上方选 <b>Base</b> 条件，逐条件诊断卡会<b>相对该 Base</b> 重新判定。</li>',
    '<li>只统计<b>已勾选</b>的条件；被<b>排除</b>的器件不计入。</li>',
    '<li>4 张分布图的<b>格式</b>（字号/线宽/透明度）在本页「🎨 格式」单独调整；<b>诊断阈值</b>（迟滞差 Δn/Δlog₁₀J₀）也在其中，改动后仅重新计算诊断卡。</li>',
    '<li>导出 PDF 时可勾选「包含等效电路分析数据」，把它放在汇总页之后。</li>',
    '<li>诊断页会检查各条件的<b>扫描步长/停留时间</b>是否一致；若不一致，顶部提示「跨条件扫描协议不一致，迟滞指标不可直接比较」。</li></ul>',
    '<h3>注意事项</h3>',
    '<ul><li>本页判定是<b>参考性解读</b>（基于参数统计的相对与绝对阈值），不是实验结论——下结论前请结合原始记录。</li>',
    '<li>Rsh 对低压段斜率不敏感，拟合值仅参考；Rs/Rsh 一律以仪器 given 值为准。</li>',
    '<li><b>方法局限（重要）</b>：此方法基于四个理想假设（光生电流≈Jsc 恒定、Rs≈0、Rsh→∞、纯二极管方程），钙钛矿中均不严格成立（离子迁移、电压依赖光生电流、迟滞、Rs 上拐区干扰）。因此提取的 n/J₀ 是<b>表观值</b>，宜用于同批器件的相对比较，不宜声称本征复合理想因子；n&gt;2 在钙钛矿中无法用传统 SRH/辐射复合直接解释，解读需谨慎。</li>',
    '<li>若需<b>本征参数</b>：Suns-Voc（n = q/kT·ΔVoc/ΔlnI_light）是分析复合相关理想因子行为的重要参照方法之一，可显著降低 Rs 对结果的干扰，但在钙钛矿中仍可能受到离子-电子耦合与界面状态影响，宜与暗态 JV、阻抗谱或稳态/漂移扩散分析交叉验证；或先做 Rs 修正（V<sub>int</sub>=V+J·Rs）再拟合、严格限定窗口（0.3~0.8Voc 且跨度≥2 个数量级），并注明「表观」。</li>',
    '<li>某些数据对数线性区采样过少（分辨率不足）会显示 N/A，属正常现象。</li>',
    '<li>若数据包含暗态 JV 曲线，可结合暗电流分析获得更严格的本征参数（暗态指数区可避免光生电流代理假设，但仍需检查扫描方向与离子动态——离子迁移不因关灯消失，暗态同样可能存在正反扫差异）。</li>',
    '<li>诊断卡结论为<b>推测性参考</b>（均带「可能」措辞），用于快速圈定排查方向，例如「n 偏高 → 可能为缺陷复合增强，建议排查界面钝化/退火」；它不是实验定论——本工具为器件优化的快速筛选手段，方法局限与本页注意事项即免责范围，最终结论需结合暗态 JV、Suns-Voc、界面/接触表征复核。</li></ul>'
  ].join('');

  var corrHelp = [
    '<h3>关于「参数相关性分析」</h3>',
    '<p>把每台器件的多个参数（PCE/Voc/Jsc/FF + Rs/Rsh + n/J₀）排成一行，两两算 <b>皮尔逊相关系数 r</b> 并做<b>显著性检验</b>，用一张热图回答：<b>这批器件的性能差异，到底主要由哪个参数驱动？各参数之间有没有内在联动？</b></p>',
    '<div class="h-eq">r = Σ(x−x̄)(y−ȳ) / √(Σ(x−x̄)²·Σ(y−ȳ)²)，　t = r·√((n−2)/(1−r²)) → 双尾 p</div>',
    '<h3>如何读 r 与星号</h3>',
    '<table><tr><th>|r|</th><th>相关强度</th><th>备注</th></tr>',
    '<tr><td>0–0.3</td><td>弱 / 可忽略</td><td>一般不看</td></tr>',
    '<tr><td>0.3–0.5</td><td>中等</td><td>结合显著性</td></tr>',
    '<tr><td>0.5–0.7</td><td>强</td><td>—</td></tr>',
    '<tr><td>0.7–1.0</td><td>很强</td><td>通常 p&lt;0.001（***）</td></tr></table>',
    '<p>星号：* p&lt;0.05、** p&lt;0.01、*** p&lt;0.001；<b>仅关注带星号的相关</b>（样本小、偶然的 r 会被显著性挡住）。矩阵每个格子的 r 基于两参数都有效的器件对（成对 n）。</p>',
    '<h3>如何读矩阵（三步）</h3>',
    '<ol><li>对角恒为 1，跳过；</li>',
    '<li>看 <b>PCE 行/列</b>：与 Voc/Jsc/FF/Rs… 谁的 |r| 最大且显著 → 那就是本批效率的主驱动参数；</li>',
    '<li>看参数之间的联动（如 FF↔log₁₀J₀ 强负 → 复合在压 FF；n↔log₁₀J₀ 强正 → 两项同源于非理想/迟滞成分，自洽）。</li></ol>',
    '<h3>如何读散点</h3>',
    '<ul><li>点矩阵任意格 → 下方散点；灰虚线为最小二乘拟合，标题给出 r / p / 星号 / 成对 n / R²。</li>',
    '<li>点按条件分色；悬停可见「条件 · 器件号」，便于回查原始记录。</li>',
    '<li>落在趋势带外很远的点是「离群」——多为异常器件（夹针/破损/漏电），建议单独核查。</li>',
    '<li><b>条件控制</b>：散点上方可勾选/取消条件——只看某几个条件时，矩阵与散点都会按所选子集重算（选择状态跨格保持），拟合线也随之变化。</li></ul>',
    '<h3>示例</h3>',
    '<p>某批（8 条件、87 台）矩阵给出：PCE×Jsc=0.92***、PCE×FF=0.87***、FF×log₁₀J₀=−0.97***、n×log₁₀J₀=0.91***、PCE×Rs=−0.48***。</p>',
    '<p>读数：<b>效率以 Jsc 和 FF 为主驱动</b>；FF 被复合强度强烈左右（J₀ 越高 FF 越低）；Rs 与效率负相关提示有串联损耗正在拖累部分器件；n 与 J₀ 自洽 → 复合是这套体系的主轴之一。综合参考结论一起看，就可圈定下一轮工艺改进方向。</p>',
    '<h3>使用方法</h3>',
    '<ul><li>「🔗 相关性分析」打开；矩阵与散点只基于<b>已勾选</b>条件、被<b>排除</b>器件不计入。</li>',
    '<li>条件开关在散点上方；默认全选（全量分析），可按需仅保留部分条件。</li>',
    '<li>点矩阵格换散点；选择状态跨格保持。</li>',
    '<li>页面会给出「参考性结论」（基于显著信号的解读），供快速把握。</li>',
    '<li>矩阵与散点的 n/J₀ 可取三种口径：<b>平均（汇总）</b>（默认，正反扫平均——统计汇总值，非单一物理状态）/ <b>反扫</b> / <b>正扫</b>，在散点上方「n/J₀ 口径」下拉切换；切换后矩阵、散点与参考结论即时重算。PCE/Voc/Jsc/FF 始终按反扫优先口径。</li></ul>',
    '<h3>注意事项</h3>',
    '<ul><li>相关 ≠ 因果：强相关可能来自共同上游（如同一工艺批次），不直接等于直接因果。</li>',
    '<li>样本太小（成对 n&lt;8）时显著性不可靠，结论会谨慎措辞。</li>',
    '<li>建议先看全部数据的矩阵定方向，再用条件开关窄化验证。</li></ul>'
  ].join('');

  /* ---- i18n：英文完整译本（v1.1；与中文全文逐段对应） ---- */
  var equivHelp_en = [
    '<div class="h-warn">⚠ <b>Read before you read:</b> all n / J₀ on this page are <b>apparent values</b> (extracted by the light JV log-linear method; affected by hysteresis, Rs and ion migration). When the forward/reverse hysteresis is significant, the diagnostic cards show a ⚠ warning. n / J₀ are for <b>relative comparison within the same batch and scan protocol</b> — do NOT quote them as intrinsic parameters. Suns-Voc is one of the important reference methods for recombination-limited ideality behavior; it largely removes the Rs interference, but in perovskites it may still be affected by ion–electron coupling and interface states, so cross-check with dark JV, impedance spectroscopy or steady-state / drift-diffusion analysis. A ⚠ hysteresis warning is expected and does NOT mean the device failed.</div>',
    '<h3>About "Apparent Parameters & Hysteresis (engineering screening)"</h3>',
    '<p>The JV curve of a photovoltaic cell (perovskite, etc.) is usually described with the <b>single-diode equivalent circuit</b> — a handful of physically meaningful numbers that compress a whole curve, answering: <b>which step in this device / this condition is losing the efficiency?</b></p>',
    '<p><b>Purpose</b>: this page is an <b>engineering screening & anomaly localization</b> tool for relative comparison and troubleshooting hints within the same batch. It is <b>not</b> an intrinsic-parameter extraction method — apparent indicators obtained under light at finite scan rate must not be cited as intrinsic device properties.</p>',
    '<div class="h-eq">J = J<sub>L</sub> − J<sub>0</sub>[exp((V + J·R<sub>s</sub>)/a) − 1] − (V + J·R<sub>s</sub>)/R<sub>sh</sub>,　a = n·kT/q</div>',
    '<h3>The four parameters</h3>',
    '<table><tr><th>Parameter</th><th>Physical meaning</th><th>Anomalous behavior when high</th><th>Where to check</th></tr>',
    '<tr><td><b>Rs</b> series resistance</td><td>Series impedance of bulk / contact / electrode; higher limits the current more</td><td>FF and Voc both drop</td><td>Front electrode, transport-layer contact, silver grid</td></tr>',
    '<tr><td><b>Rsh</b> shunt resistance</td><td>Leakage path; lower makes shorting worse</td><td>Pinholes / leakage; Jsc and FF impaired</td><td>Interface passivation, annealing, film-thickness uniformity</td></tr>',
    '<tr><td><b>n</b> ideality factor</td><td>Apparent ideality factor (light, finite scan rate; affected by hysteresis / ionic processes)</td><td>Voc loss</td><td>Interface / bulk defect recombination</td></tr>',
    '<tr><td><b>J₀</b> saturation current density</td><td>Apparent J₀ (extrapolated: intercept of the fitted line at V=0; the absolute threshold 1e-5 mA/cm² is an empirical / uncalibrated value — prefer Δlog₁₀J₀ vs Base or within-batch quantiles)</td><td>Low Voc</td><td>Passivation quality, energy-level alignment</td></tr></table>',
    '<h3>Extraction method</h3>',
    '<p><b>Rs / Rsh</b>: taken directly from the Rs/Rsh columns of the instrument raw data, converted to the area-normalized scale (Ω·cm², = instrument value × area) for cross-batch and absolute-threshold reference (current batch area 0.0625 cm²). The instrument values are currently consistent with the "absolute Ω" scale (see the unit note in the Rs-correction section); field definitions pending instrument-manual confirmation.</p>',
    '<p><b>n / J₀</b>: <b>light log-linear fitting</b> in the upper-knee region (J &lt; 0): dark diode current J<sub>d</sub> ≈ J<sub>sc</sub>−J ≈ J₀·exp(V/(n·kT/q)); linear regression of <code>ln(J<sub>sc</sub>−J) ~ V</code> yields n from the slope and J₀ from the intercept. Stable and interpretable, intended for <b>relative engineering comparison within the same batch</b>; the extracted quantities are <b>apparent parameters</b> (see notes).</p>',
    '<h3>Two-direction fitting (reverse / forward / summary)</h3>',
    '<p><b>Reverse and forward scans are fitted separately</b>: the same device simultaneously reports reverse-scan n<sub>rev</sub> / J₀,rev and forward-scan n<sub>fwd</sub> / J₀,fwd.</p>',
    '<ul><li><b>Summary basis</b>: for devices with both directions, n is the <b>arithmetic mean</b> and J₀ the <b>geometric mean</b> (log₁₀ average) of the two directions — this is the default basis for the charts and diagnostic cards on this page; for single-direction devices, that direction is used (the card notes the direction). Forward and reverse scans correspond to device states under different scan histories; the mean is a <b>statistical summary</b>, not a single physical state.</li>',
    '<li><b>Hysteresis difference</b>: for devices with valid data in both directions, Δn = |n<sub>rev</sub>−n<sub>fwd</sub>| and Δlog₁₀J₀ = |log₁₀J₀,rev − log₁₀J₀,fwd|; the condition-level median appears on the "two-direction" row of the diagnostic card.</li>',
    '<li><b>Directional hysteresis</b>: besides the absolute differences, signed direction differences δn = n<sub>fwd</sub> − n<sub>rev</sub>, δlog₁₀J₀ = log₁₀J₀,fwd − log₁₀J₀,rev are reported, together with the fraction of devices with higher forward-scan values — this distinguishes "large hysteresis but random direction" from "systematically higher forward scan across the batch", the latter being more worth a process investigation.</li>',
    '<li><b>Fit-quality grading</b>: n / J₀ results are graded <b>A / B / C</b> by fit quality — <b>A reliable</b> (can enter condition statistics), <b>B reference</b>, <b>C trend only</b> (greyed out); based on the number of valid points N, voltage span ΔV, confidence-interval width and window stability. The thresholds are illustrative and need instrument-specific calibration. The "fit coverage" row of the diagnostic card shows successful / total fits and the A/B/C fractions.</li>',
    '<li><b>Thresholds & warnings</b>: since Δn and Δlog₁₀J₀ have different scales, two thresholds are used: the <b>Δn threshold</b> (default <b>0.5</b>, triggers the main warning) and the <b>Δlog₁₀J₀ threshold</b> (default <b>1.0</b> = 10×, supporting evidence / auxiliary hint only, never triggers the main warning alone). Both are adjustable under "🎨 Style → Diagnostic thresholds" → the diagnostic card then shows a <b>⚠ hysteresis warning</b>, noting that n / J₀ are apparent and may contain hysteresis / measurement artifacts. Larger thresholds reduce false alarms but may miss real ones; smaller are more sensitive but prone to false alarms — they only affect the "read with caution" hint and <b>do not judge a device as failed</b>.</li>',
    '<li><b>Important</b>: hysteresis strongly depends on <b>scan rate, scan range, pre-bias / preconditioning and scan-order</b>, and may vary <b>non-monotonically</b> with scan rate (too slow approaches quasi-steady state; too fast leaves ions no time to respond; intermediate time scales can be worst); therefore Δn and Δlog₁₀J₀ across different protocols are not directly comparable — comparison holds only within the same batch and scan protocol.</li></ul>',
    '<h3>Rs correction (optional)</h3>',
    '<p>The series resistance Rs shifts the junction voltage from the applied voltage: <b>V<sub>int</sub> = V − J·R<sub>s</sub></b> (J&lt;0, hence V<sub>int</sub>&gt;V); when enabled, n / J₀ are re-fitted on the corrected voltage axis.</p>',
    '<p><b>Location & default</b>: the switch is at "🎨 Style → Diagnostic thresholds → Rs correction", <b>off by default</b>. When enabled, the four distribution charts and diagnostic cards <b>recompute immediately with the corrected basis</b> and the chart titles are marked "Rs corrected".</p>',
    '<p><b>Recommendation</b>: the fit window (|J| = 10%–90% of Jsc) already avoids the region closest to Jsc, where series-resistance interference is strongest; for typical batches the single Rs correction (even with the correct area-normalized scale) does not improve fit quality in our tests, so it stays off by default to keep this method stable as an empirical relative indicator. Only for batches with large Rs, or when the fit window is forced close to Jsc, you may enable it — and re-verify with the fit linearity (r²) and physical plausibility of the parameters.</p>',
    '<p><b>Unit note</b>: the correction uses the area-normalized Rs·A (Ω·cm²). The instrument Rs is consistent with the "absolute Ω" scale (current batch area 0.0625 cm², Rs·A median ≈ 2 Ω·cm²); field definitions still pending instrument-manual / independent-slope verification. A near-Jsc local-slope cross-check gives: slope ≈ Rsh·A (1484 vs 1650 Ω·cm²), supporting the absolute-Ω interpretation of Rsh.</p>',
    '<h3>Worked example</h3>',
    '<p>A batch: <b>PVK-S1 (control)</b> and <b>PVK-S2</b>, 12 devices each; median parameters (n / J₀ on the two-direction summary basis):</p>',
    '<table><tr><th>Sample</th><th>Rsh (Ω)</th><th>Rs (Ω)</th><th>n main</th><th>fwd / rev n</th><th>Δn</th><th>J₀ (mA/cm²)</th><th>Reading</th></tr>',
    '<tr><td>PVK-S1</td><td>≈22k</td><td>≈31</td><td>1.87</td><td>2.11 / 1.63</td><td>0.48</td><td>3e−9</td><td>Δn close to the 0.5 threshold → hysteresis note, healthy</td></tr>',
    '<tr><td>PVK-S2</td><td>≈15k</td><td>≈33</td><td>2.14</td><td>2.4 / 1.9</td><td>0.5</td><td>2e−8</td><td>n / J₀ high → check passivation / annealing (hysteresis-affected, read with care)</td></tr></table>',
    '<p>Direction of the conclusion: the PVK-S2 difference is neither in the contact (similar Rs) nor in leakage (Rsh still acceptable), but in <b>stronger recombination (higher n, J₀)</b> — pointing to passivation / interface treatment rather than the absorber. However, both Δn values are near the threshold, so the apparent n contains a hysteresis contribution; final conclusions need the same-condition forward/reverse curves and Suns-Voc re-check.</p>',
    '<h3>How to use</h3>',
    '<ul><li>Open via "⚡ Apparent parameters" in the toolbar; pick the <b>Base</b> condition above — the per-condition diagnostic cards re-evaluate <b>relative to that Base</b>.</li>',
    '<li>Only <b>checked</b> conditions are included; <b>excluded</b> devices are not counted.</li>',
    '<li>The four distribution charts have their own <b>style</b> (font size / line width / alpha) under "🎨 Style" here; the <b>diagnostic thresholds</b> (hysteresis Δn / Δlog₁₀J₀) are also there; changes only recompute the diagnostic cards.</li>',
    '<li>When exporting PDF you can tick "Include apparent-parameter diagnostics" to place it after the summary page.</li>',
    '<li>The page checks whether all conditions share the same <b>scan step / dwell time</b>; if not, a banner warns "scan protocol differs across conditions — hysteresis metrics are not directly comparable".</li></ul>',
    '<h3>Notes</h3>',
    '<ul><li>Judgments on this page are <b>reference interpretations</b> (based on relative & absolute thresholds of parameter statistics), not experimental conclusions — consult the raw records before concluding.</li>',
    '<li>Rsh is not sensitive to the low-voltage slope; its fitted value is reference only. Rs / Rsh always follow the instrument-given values.</li>',
    '<li><b>Method limitations (important)</b>: this method rests on four ideal assumptions (photocurrent ≈ Jsc constant, Rs≈0, Rsh→∞, pure diode equation); none hold strictly in perovskites (ion migration, voltage-dependent photocurrent, hysteresis, Rs interference at the upper knee). The extracted n / J₀ are therefore <b>apparent values</b>, useful for relative comparison within a batch, not for claiming an intrinsic recombination ideality factor; n&gt;2 in perovskites cannot be explained directly by classical SRH / radiative recombination — interpret with care.</li>',
    '<li>If you need <b>intrinsic parameters</b>: Suns-Voc (n = q/kT·ΔVoc/ΔlnI_light) is an important reference for recombination-limited ideality behavior and largely removes the Rs interference, but in perovskites it can still be affected by ion–electron coupling and interface states — cross-check with dark JV, impedance spectroscopy or steady-state / drift-diffusion analysis; alternatively apply the Rs correction (V<sub>int</sub>=V+J·Rs) before fitting, strictly restrict the window (0.3–0.8 Voc and ≥2 decades), and label the results "apparent".</li>',
    '<li>Some datasets have too few samples in the log-linear region (insufficient resolution) and show N/A — this is normal.</li>',
    '<li>If dark JV curves are available, combine them with dark-current analysis for stricter intrinsic parameters (the dark exponential region avoids the photocurrent-proxy assumption; still check scan direction and ion dynamics — ion migration does not disappear with the light off, and forward/reverse differences may exist in the dark too).</li>',
    '<li>Card conclusions are <b>speculative references</b> (always phrased with "may / possibly") to quickly narrow down investigations, e.g. "n high → possibly enhanced defect recombination; check interface passivation / annealing". They are not experimental verdicts — this tool is a quick screening aid for device optimization; the method limitations and the notes on this page are the disclaimer scope; final conclusions should be re-verified with dark JV, Suns-Voc and interface / contact characterization.</li></ul>'
  ].join('');

  var corrHelp_en = [
    '<h3>About "Parameter correlation analysis"</h3>',
    '<p>Arrange the parameters of each device (PCE / Voc / Jsc / FF + Rs / Rsh + n / J₀) in a row, and compute the <b>Pearson correlation coefficient r</b> between each pair with a <b>significance test</b>, answering in one heatmap: <b>which parameter drives the performance spread of this batch, and are the parameters internally linked?</b></p>',
    '<div class="h-eq">r = Σ(x−x̄)(y−ȳ) / √(Σ(x−x̄)²·Σ(y−ȳ)²),　t = r·√((n−2)/(1−r²)) → two-tailed p</div>',
    '<h3>How to read r and the significance stars</h3>',
    '<table><tr><th>|r|</th><th>Correlation strength</th><th>Note</th></tr>',
    '<tr><td>0–0.3</td><td>weak / negligible</td><td>usually ignored</td></tr>',
    '<tr><td>0.3–0.5</td><td>moderate</td><td>consider with significance</td></tr>',
    '<tr><td>0.5–0.7</td><td>strong</td><td>—</td></tr>',
    '<tr><td>0.7–1.0</td><td>very strong</td><td>usually p&lt;0.001 (***)</td></tr></table>',
    '<p>Stars: * p&lt;0.05, ** p&lt;0.01, *** p&lt;0.001; <b>only pay attention to starred correlations</b> (with small samples, accidental r is blocked by significance). Each matrix cell uses device pairs where both parameters are valid (paired n).</p>',
    '<h3>How to read the matrix (three steps)</h3>',
    '<ol><li>The diagonal is always 1 — skip it;</li>',
    '<li>Look at the <b>PCE row / column</b>: whichever of Voc / Jsc / FF / Rs… has the largest |r| and is significant is the main driver of this batch\'s efficiency;</li>',
    '<li>Look at inter-parameter links (e.g. FF↔log₁₀J₀ strongly negative → recombination is squeezing FF; n↔log₁₀J₀ strongly positive → both stem from non-ideal / hysteresis components — self-consistent).</li></ol>',
    '<h3>How to read the scatter</h3>',
    '<ul><li>Click any matrix cell → the scatter below; the grey dashed line is the least-squares fit; the title gives r / p / stars / paired n / R².</li>',
    '<li>Points are colored by condition; hovering shows "condition · device #" for cross-checking raw records.</li>',
    '<li>Points far off the trend band are "outliers" — mostly anomalous devices (probe miscontact / damage / leakage); check them individually.</li>',
    '<li><b>Condition control</b>: check / uncheck conditions above the scatter — with only some conditions selected, both matrix and scatter recompute on that subset (selection persists across cells) and the fit line follows.</li></ul>',
    '<h3>Worked example</h3>',
    '<p>A batch (8 conditions, 87 devices) gives: PCE×Jsc=0.92***, PCE×FF=0.87***, FF×log₁₀J₀=−0.97***, n×log₁₀J₀=0.91***, PCE×Rs=−0.48***.</p>',
    '<p>Reading: <b>efficiency is driven mainly by Jsc and FF</b>; FF is strongly pulled by recombination strength (higher J₀ → lower FF); Rs negatively correlates with efficiency, suggesting a series-resistance loss dragging some devices; n and J₀ are self-consistent → recombination is one of the main axes of this system. Put together with the reference conclusions, this narrows the next round of process improvement.</p>',
    '<h3>How to use</h3>',
    '<ul><li>Open via "🔗 Correlation analysis"; matrix and scatter are based on <b>checked</b> conditions only, <b>excluded</b> devices not counted.</li>',
    '<li>Condition switches are above the scatter; default all checked (full analysis); keep only part of the conditions as needed.</li>',
    '<li>Click a matrix cell to switch scatter; selection persists across cells.</li>',
    '<li>The page gives "reference conclusions" (interpretations based on significant signals) for a quick grip.</li>',
    '<li>n / J₀ in matrix and scatter have three bases: <b>Average (summary)</b> (default, mean of forward & reverse — a statistical summary, not a single physical state) / <b>Reverse scan</b> / <b>Forward scan</b>, switched via the "n/J₀ basis" dropdown; matrix, scatter and reference conclusions recompute immediately. PCE / Voc / Jsc / FF always use the reverse-scan-first basis.</li></ul>',
    '<h3>Notes</h3>',
    '<ul><li>Correlation ≠ causation: a strong correlation may come from a common upstream (e.g. the same process batch); it does not equal direct causation.</li>',
    '<li>With too-small samples (paired n&lt;8), significance is unreliable and conclusions are phrased cautiously.</li>',
    '<li>First read the full-data matrix to set direction, then narrow with the condition switches.</li></ul>'
  ].join('');


  var namegroupsHelp = [
    '<h3>这个页面做什么</h3>',
    '<p>仪器导出的文件里，一个样品（条件）常有多次测量，名称只差最后一段（如 PVK-A-CH1、PVK-A-CH2 是 PVK-A 的第 1、2 次测量）。本页把相似的名称归成组：一组 = 一个条件，组内的多次测量会作为这个条件的多个器件一起统计、画图。</p>',
    '<h3>三个概念</h3>',
    '<ul><li><b>条件</b>：要放在一起比较的样品或工艺（如 PVK-A、PVK-B）。</li>',
    '<li><b>通道 / 次数</b>：同一样品的第几次测量（如 CH1、CH2）。</li>',
    '<li><b>方向</b>：正扫 / 反扫。工具按名称与曲线自动识别；识别不了的只按条件名显示，不硬标方向。</li></ul>',
    '<h3>怎么用</h3>',
    '<ol><li>打开页面，上方是工具找好的<b>组卡</b>：一组同款名称一张卡，卡上有代表名和条数。</li>',
    '<li>点组卡「归并」：这一组当作一个条件；「排除」：不归并，维持原样；「详情」：展开这组里全部名称。</li>',
    '<li>组卡菜单（▾）：合并为条件 / 保持分开 / 重命名 / 应用规则到全部（同款命名按同一规则处理）。</li>',
    '<li>下面每个名称拆成彩色积木：点积木手动指定 条件 / 通道 / 方向 / 忽略；改了之后预览数字会立刻更新。</li>',
    '<li>确认无误点「应用」；应用错了点「恢复原始分组」——立即还原到应用前的原始分组。</li></ol>',
    '<h3>常见问题</h3>',
    '<ul><li>名称看不懂？不需要看懂——只需检查工具自动分好的组是否合理。</li>',
    '<li>只测过一次的样品（如 PVK-C）会单独成组，条数=1。</li>',
    '<li>改错了？点「保持原样」关闭页面，数据不受影响。</li>',
    '<li>不确定一个数是不是漏了：组卡条数加起来应等于文件里的测量次数。</li></ul>',
    '<p><b>注意</b>：工具只改变分组方式，不会改写名称。</p>'
  ].join('');
  var namegroupsHelp_en = [
    '<h3>What this page does</h3>',
    '<p>Instrument exports often list one sample (condition) several times, with names differing only at the end (e.g. PVK-A-CH1, PVK-A-CH2 = 1st and 2nd runs of PVK-A). This page groups similar names: one group = one condition; the runs inside become multiple devices of that condition for statistics and plots.</p>',
    '<h3>Three concepts</h3>',
    '<ul><li><b>Condition</b>: the sample or process you want to compare (e.g. PVK-A, PVK-B).</li>',
    '<li><b>Channel / run</b>: which measurement of the same sample (e.g. CH1, CH2).</li>',
    '<li><b>Direction</b>: forward / reverse scan, auto-detected from names and curves; if undetectable, only the condition name is shown and no direction is forced.</li></ul>',
    '<h3>How to use</h3>',
    '<ol><li>Open the page: the top shows <b>group cards</b> — one card per set of similar names, with a representative name and count.</li>',
    '<li>Card "Merge": treat that group as one condition; "Exclude": keep as is; "Details": expand all member names.</li>',
    '<li>Card menu (▾): merge as one condition / keep separate / rename / apply rule to all (same treatment for every same-pattern set).</li>',
    '<li>Below, each name is split into coloured blocks: click a block to assign condition / channel / direction / ignore; preview numbers update immediately.</li>',
    '<li>Click "Apply" when done; "Clear rules" returns to automatic detection.</li></ol>',
    '<h3>FAQ</h3>',
    '<ul><li>Do the names look cryptic? You do not need to read them — just check whether the auto groups are sensible.</li>',
    '<li>A sample measured once (e.g. PVK-C) becomes its own group with count 1.</li>',
    '<li>Made a mistake? "Keep as is" closes the page with no change to the data.</li></ul>',
    '<p><b>Note</b>: grouping only; names are never rewritten.</p>'
  ].join('');
  global.JVHelpContent = {
    equiv: equivHelp,
    corr: corrHelp,
    equiv_en: equivHelp_en,
    corr_en: corrHelp_en,
    namegroups: namegroupsHelp,
    namegroups_en: namegroupsHelp_en,
    titles: { equiv: { zh: '表观参数与迟滞诊断 · 说明', en: 'Apparent Parameters & Hysteresis · Help' }, corr: { zh: '参数相关性分析 · 说明', en: 'Parameter Correlation · Help' }, namegroups: { zh: '条件分组 · 说明', en: 'Condition Grouping · Help' } }
  };
})(typeof window !== 'undefined' ? window : globalThis);
